const REST = 10000
const EXERCISE = 30000
export const steps = [
    {
        step: 'Starting workout in 5 seconds',
        key: 'readyFor7MinuteIntro',
        type: 'rest',
        timer: 'readyFor7MinuteIntroTimer',
        spriteTime: 5000,
        elapsedTime: 5000,
    },
    {
        step: 'Jumping jacks',
        key: 'jumpingJacks',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 4000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Wall sit',
        key: 'wallSit',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 4000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Push up',
        key: 'pushUp',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 2000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Abdominal crunch',
        key: 'abCrunch',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 3000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Step-up onto chair',
        key: 'stepUpToChair',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 4000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Squat',
        key: 'squat',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 3000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Triceps dip on chair',
        key: 'tricepDipOnChair',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 3000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Plank',
        key: 'plank',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 4000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'High knees running in place',
        key: 'highKnee',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 5000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Lunge',
        key: 'lunge',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 2000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Push ups with rotation',
        key: 'pushUpRotation',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 5000,
        elapsedTime: EXERCISE,
    },
    {
        step: 'Rest for 10 seconds',
        key: 'rest',
        type: 'rest',
        timer: 'restTimer',
        spriteTime: 4000,
        elapsedTime: REST,
    },
    {
        step: 'Side plank',
        key: 'sidePlank',
        type: 'exercise',
        timer: 'timer',
        spriteTime: 3000,
        elapsedTime: EXERCISE,
    },
]

export const sprite = {
    readyFor7MinuteIntro: [0, 5000],
    readyFor7MinuteIntroTimer: [5000, 5000],
    timer: [14000, 30000],
    rest: [45000, 4000],
    restTimer: [49000, 10000],
    done: [98000, 6000],
    highFive: [104000, 1000],

    jumpingJacks: [10000, 4000],
    wallSit: [59000, 4000],
    pushUp: [63000, 2000],
    abCrunch: [66000, 3000],
    stepUpToChair: [69000, 4000],
    squat: [73000, 3000],
    tricepDipOnChair: [76000, 3000],
    plank: [79000, 4000],
    highKnee: [83000, 5000],
    lunge: [88000, 2000],
    pushUpRotation: [90000, 5000],
    sidePlank: [95000, 3000],
}